openapi: 3.0.1
info:
  title: myApi
  description: API Definition of myApi
  version: 1.0.0
servers:
- url: http://localhost:8290/myapi
paths:
  /firstresource:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /newapi:
    get:
      responses:
        default:
          description: Default response
